### ISSUE TITLE
Add a new column to ietf-language-tags to indicate the unicode-cldr defaults

### ISSUE THREAD

**Issue by ppKrauss** [datasets/language-codes#5]
There are an official list of all "default langs", [`unicode-cldr/cldr-core/defaultContent.json`](https://github.com/unicode-cldr/cldr-core/blob/master/defaultContent.json). They are defined in the [3rd bullet under design goals](http://cldr.unicode.org/development/development-process/design-proposals/json-packaging) of `cldr.unicode.org/development/development-process/design-proposals`: 

> Default content locales - In order to keep the data size to a minimum, JSON data for default content locales will not be included in the installable packages.  Since all default content locales can retrieve their data from the parent via simple inheritance ( i.e. removal of the rightmost portion of the language tag ), this should be relatively easy for most JavaScript applications to determine the appropriate location from which to retrieve the data.  A new JSON file "defaultContent.json" shall be included in CLDR's as part of the cldr-core package, in the top level directory,  that will contain the list of default content locales for the release.

This information about what [ietf-language-tags](https://github.com/datasets/language-codes/blob/master/data/ietf-language-tags.csv) are the "defaultContent" can be added to the `ietf-language-tags.csv` as a new column, `dftLang` (with boolean 0/1 values).

**Comment by ppKrauss** [comment]
Ops, sorry, more two comments:
- Thanks to @JCEmmons at [unicode-cldr/cldr-json/issues](https://github.com/unicode-cldr/cldr-json/issues/6#issuecomment-103080492), by your clues and explanations.
- See `datapackage.json`  at my fork after pull request.

**Comment by rufuspollock** [comment]
@ppKrauss thanks for this - great work!
